---
- hosts: local
  connection: local
  tasks:
    - name: remove old host key
      shell: ssh-keygen -R "{{item}}" 
      with_items:
        - 192.168.86.133
        - 192.168.86.134
        - 192.168.86.135

    - name: update key
      shell: ssh-keyscan -H "{{item}}" >> /home/linuxroot/.ssh/known_hosts
      with_items:
        - 192.168.86.133
        - 192.168.86.134
        - 192.168.86.135        
